### PR TITLE
Fix bug preferred mode of communication edit

### LINKED ISSUE #259: [PE-D][Tester E] Edit message does not tally with result
Dear F12-2,

Image
I have this dummy contact with pm being telegram

Image
I execute a clear telegram command here

Image

Expected: command message should not display pm\telegram
Actual: command message still displays pm\telegram

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Derekqua**
close #259

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -147,21 +147,33 @@ private static Pair<Person, TagUpdateResult> createEditedPersonAndResult(
...
+        boolean shouldClearPreferredMode = currentMode != null && !availableModes.contains(currentMode);
+
+        // If the preferred mode is no longer valid, create a new Person with NONE preferred mode
+        if (shouldClearPreferredMode) {
+            editedPerson = new Person(editedPerson.getName(), editedPerson.getPhone(), editedPerson.getEmail(),
+                    editedPerson.getTelegram(), editedPerson.getGithub(), PreferredCommunicationMode.NONE,
+                    editedPerson.getTags(), editedPerson.getPinnedAt().orElse(null)
+            );
+        }
+
```
Comment (MoshiMoshiMochi) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: low key, these changes no longer really make it a validation method, because what you're really doing here is setting the preferred mode (based on the person's `currentMode` vs `availableModes`. Maybe split the method up abit? or just rename the method to `getPreferredMode`.

Also, perhaps since we're only checking the perferredMode, there won't be a need to pass in the whole `editPersonDescriptor`. Instead we can use this  method purely as a `getPerferredMode` method which will return the correctly updated `preferredMode` to set the editperson in `createEditedPersonAndResult`

Comment (MoshiMoshiMochi) [reply src/main/java/seedu/address/logic/commands/EditCommand.java]: So basically, what I'm saying use this method to just return the correct preferredMode 👍
