### PR TITLE
Show message to user using StatusBarFootage if addressbook is corrupted

### LINKED ISSUE #156: [BUG] Invalidating the data/addressbook.json does not show any error to the user
## How to reproduce
1. Ensure that the `data/addressbook.json` file exists - if it doesn't, create a contact
2. Edit the `data/addressbook.json` file, and input an invalid character into a field.
    e.g. Put `thisGithubProfile$20<>.-!shouldNotbeValid` into the "github" field of a Person in the json
3. Run devbooks

## What Happens
The program logs that the file was invalidated, and a new addressbook is created. The blank UI is shown.

Image

## Expected Behaviour
An error message should be shown to the user that while a matching .json file was found, it was not able to load the data. Currently, this information is logged.

### On the severity classification
I filed this under `severity.Medium` as it probably only affects a very small subset of users (those nosy enough to poke around the data file), but when it happens it's pretty major and might cause a panic. Furthermore, if they add a new user, it essentially clears all their old data.

### PR DESCRIPTION
**Pull request by Harjun751**
Resolves #156 

Just want to start off by saying I don't think that this is a perfect solution, but given the time limit and our constraints, this seemed the easiest way.
image

## Add a StatusBarNotificationDispatcher
This is a singleton class that manages interfacing with the StatusBarFooter. The StatusBarFooter sets itself into the StatusBarNotificationDispatcher, and other classes can update the StatusBarFooter using the notification dispatcher. They simply need to get the instance and call notify.

I did this so as to not introduce further dependencies between the UI component and any other component that wants to show a message to the user. While using the singleton hurts testability, I think it's the easiest way to proceed if we don't want to do something like run chain calls from UIManager to MainWindow to StatusBarFooter.

## Possible improvement
Create a StatusBarHandler that extends the `Handler` class. Inject the StatusBar into the Handler once it's ready, and then in `LogCenter` set the new Handler in the logger - now, the StatusBar can receive log events and show them as they come on the bottom footer.

I didn't go with this path because it requires more initialization steps than I like - it needs to inject the StatusBar into the Handler once it's ready, and after that, the Hander has to be injected into the LogCenter. It was too much to add and test, so I didn't want to risk it.

We can consider this as an improvement for the future.

### CODE REVIEW

File: src/main/java/seedu/address/ui/StatusBarNotificationDispatcher.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    public static StatusBarNotificationDispatcher getInstance() {
+        if (instance == null) {
+            instance = new StatusBarNotificationDispatcher();
+        }
+        return instance;
+    }
+
+    /**
+     * Sets the StatusBarFooter to be used for dispatching messages.
+     * @param status The StatusBarFooter to be setting the messages on.
```
Comment (Derekqua) [inline src/main/java/seedu/address/ui/StatusBarNotificationDispatcher.java]: I think you need to add a new line before @param for consistency and readability.
