### PR TITLE
191 launch command linux inconsistent functionality

### LINKED ISSUE #144: [BUG] Update Developer Guide Logic Class Diagram
Currently the logic class diagram does not account for the CommandRegistry and CommandFactory.

Fix: Update it to ensure that class diagram to correctly reflects this

### LINKED ISSUE #191: [BUG] Launch does not work on Fedora 42 :pensive:
Running the `launch` command causes the program to freeze indefinitely.

## Investigation
Investigating the issue, the awt.desktop class seems to evaluate `desktop.isSupported` to `true`. Due to this, the program (as you would expect) uses the `desktop.browse()` function (since it's supposedly supported... as you'd expect). However, the moment that function is called, the program seems to freeze, not throwing an error or doing anything in particular

## Suggestions
At this point, it seems that linux support with the java.awt libraries is already tenuous at best. We can't really help if support on the library is already poor, let's classify this as a `WontFix` and inform linux users in the UserGuide that launch may or may not work.

### PR DESCRIPTION
**Pull request by MoshiMoshiMochi**
resolves #191
closes #144

# Changes
## `ApplicationLinkLauncher`
- Removed first attempt of trying to launch the application by checking the `java.awt.Desktop` api support before proceeding to do so
- Instead, the code relies soley on what was the previous *fallback* option `DesktopApi`
- Why? Because the `DesktopApi` will attempt to launch the application through system-specific commands first!!!!
- It will only attempt to use the `java.awt.Desktop` api **IF**
    - **the system-specific command fails**
    - **& `java.awt.Desktop` api is supported**
- Hence, this means that  there is still a possibility that if a linux OS user is able reach that point, that the code would crash.
- However, we are triggering the use of system-specific commands first in hopes that it will successfully launch.  And if it does fail, we pray that the linux OS behaves like a good boy and **DOESN'T RETURN TRUE TO CHECKS THAT ARE SPECIFICALLY MEANT TO CATCH IT ONLY FOR IT TO FAIL AFTERWARDS AHHHHHHHHHHHHH**

## `DesktopApi`
- As a result of the changes for `ApplicationLinkLauncher`, I've create a lot more test cases to hopefully account for more potential issues that can be faced by the user.
- Though the testings are purely mocks anyway and if the OS doesn't perform as expected, its still gonna crash out (kinda like me 🙃)

### Logic
- Updated `LogicUtilityClassDiagram` to accurately reflect these changes
- Also updated the text to accurately reflect these changes

### Launch Feature
- Added an important notes section to warn users about this potential issue (redirecting them to the known issues section)
### Known Issues
- Added known issue about linux os inconsistent behaviours accross distros and how that might affect launch command mileage.

### CODE REVIEW

File: src/main/java/seedu/address/logic/util/DesktopApi.java [hunk 1]
```diff
@@ -32,113 +90,144 @@ public static boolean browse(URI uri) {
...
+     * @return {@code true} if browsing succeeds, {@code false} otherwise
+     */
     static boolean browseDesktop(URI uri) {
 
-        logOut("Trying to use Desktop.getDesktop().browse() with " + uri.toString());
+        logOut(LOG_TRY_BROWSE + uri.toString());
         try {
             if (!Desktop.isDesktopSupported()) {
-                logErr("Platform is not supported.");
+                logErr(LOG_PLATFORM_NOT_SUPPORTED);
```
Comment (Harjun751) [inline src/main/java/seedu/address/logic/util/DesktopApi.java]: Would it be better to log errors here at the `fine/finer` scope? Errors here don't necessarily mean that the launch command will not work.

In the case of a Linux operating system, this will mean that at least 2 errors are logged every time a user runs a command - it would clutter the error log.

Instead, why don't we add a check in `openSystemSpecific` to see if all of the runCommands for a an OS fails. In that case, we log an error.

File: src/main/java/seedu/address/logic/util/DesktopApi.java [hunk 2]
```diff
@@ -32,113 +90,144 @@ public static boolean browse(URI uri) {
...
                 return false;
             }
 
-            if (!Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
-                logErr("BROWSE is not supported.");
+            if (!Desktop.getDesktop().isSupported(Action.BROWSE)) {
```
Comment (Harjun751) [inline src/main/java/seedu/address/logic/util/DesktopApi.java]: Can we refactor Desktop to directly expose an `isSupported()` method? As it stands, this would be a violation of the Law of Demeter. Applies to the browse call on line 153 as well.

Additionally, personally I think it would be sufficient to merge the PLATFORM_NOT_SUPPORTED and BROWSE_NOT_SUPPORT cases - logging one generic error would be sufficient, IMO?

File: src/main/java/seedu/address/logic/util/ApplicationLinkLauncher.java [hunk 3]
```diff
@@ -134,53 +101,12 @@ protected static boolean attemptOpenWithDesktop(URI uri) throws IOException, Uns
      *
      * @return <code>true</code> if the link was successfully opened.
      */
-    private static boolean tryOpenWithFallback(URI uri) {
+    private static boolean tryOpenWithDesktopApi(URI uri) {
         boolean success = DesktopApi.browse(uri);
         if (!success) {
             System.err.println("Fallback DesktopAPI failed to open link: " + uri);
```
Comment (Harjun751) [inline src/main/java/seedu/address/logic/util/ApplicationLinkLauncher.java]: Is it possible for us to use the Logger here? For additional context, our application *only* uses System.out/System.err in DesktopAPI or ApplicationLinkLauncher.

**Review by Harjun751 — APPROVED** [review]
Tested on Fedora 42 (uses `gnome-open`) and on Arch linux (uses `xdg-open`), works smoothly and as expected.

I left some readability/code-quality related comments. Up to you to incorporate them if you think it makes sense or improves the code!

File: src/main/java/seedu/address/logic/util/ApplicationLinkLauncher.java (hunk 3 above)
Comment (MoshiMoshiMochi) [reply src/main/java/seedu/address/logic/util/ApplicationLinkLauncher.java]: Noted

**Review by Harjun751 — APPROVED** [review]
Pray we don't have to touch this again

Image
