### PR TITLE
175 improve invalid index error message

### LINKED ISSUE #175: [Suggestion] Improve invalid index error message for edit command
The current error message for an invalid index is too vague and does not guide the user on how to correct it.

Suggested Changes:
Update the error message to include the number of available contacts and a helpful suggestion, for example: Error: Invalid contact index 99. There are currently 12 contacts — use 'list' to view valid indices.

Reason:
Provides clearer feedback and helps users understand why the error occurred and how to fix it.

Image

### PR DESCRIPTION
**Pull request by MoshiMoshiMochi**
resolves #175 

## Changes
- Created a static method `getMessageInvalidPersonDisplayedIndex`, which takes in a 2 integers (targetIndex, size), in Message which can be used to format the new error messages.
- Updated all references to `MESSAGE_INVALID_PERSON_DISPLAYED_INDEX` to call `getMessageInvalidPersonDisplayedIndex` method instead.

image

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -14,7 +14,8 @@ public class Messages {
 
     public static final String MESSAGE_UNKNOWN_COMMAND = "Unknown command";
     public static final String MESSAGE_INVALID_COMMAND_FORMAT = "Invalid command format! \n%1$s";
-    public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The person index provided is invalid";
+    public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX =
+            "Invalid (Out Of Bounds) index %d. There are only %d contacts in the current displayed list";
```
Comment (Derekqua) [inline src/main/java/seedu/address/logic/Messages.java]: Good job adding a more specific error message. It provides clearer feedback and helps users understand why the error occurred and how to fix it.

**Review by Derekqua — APPROVED** [review]
